Repository robotology/bayes-filters-lib, pull requests merged in 2018-12, with the labels that each got.

#7 Implement unscented transform utilities
  CHANGELOG.md
  src/BayesFilters/include/BayesFilters/sigma_point.h
  src/BayesFilters/src/sigma_point.cpp
  test/test_SigmaPointUtils/main.cpp
Labels: documentation, enhancement

#9 Improve state and measurement models
  CHANGELOG.md
  src/BayesFilters/CMakeLists.txt
  src/BayesFilters/include/BayesFilters/AdditiveMeasurementModel.h
  src/BayesFilters/include/BayesFilters/AdditiveStateModel.h
  src/BayesFilters/include/BayesFilters/ExogenousModel.h
  src/BayesFilters/include/BayesFilters/LinearMeasurementModel.h
  src/BayesFilters/include/BayesFilters/MeasurementModel.h
  src/BayesFilters/include/BayesFilters/MeasurementModelDecorator.h
  src/BayesFilters/include/BayesFilters/SimulatedLinearSensor.h
  src/BayesFilters/include/BayesFilters/SimulatedStateModel.h
  src/BayesFilters/include/BayesFilters/StateModel.h
  src/BayesFilters/include/BayesFilters/StateModelDecorator.h
  src/BayesFilters/include/BayesFilters/WhiteNoiseAcceleration.h
  src/BayesFilters/src/AdditiveMeasurementModel.cpp
  src/BayesFilters/src/MeasurementModelDecorator.cpp
  src/BayesFilters/src/SimulatedLinearSensor.cpp
  src/BayesFilters/src/SimulatedStateModel.cpp
  src/BayesFilters/src/StateModel.cpp
  src/BayesFilters/src/StateModelDecorator.cpp
  src/BayesFilters/src/WhiteNoiseAcceleration.cpp
Labels: enhancement

#10 Handle noise augmentation in class Gaussian Mixture
  src/BayesFilters/include/BayesFilters/GaussianMixture.h
  src/BayesFilters/src/GaussianMixture.cpp
  test/test_Gaussian/main.cpp
Labels: enhancement

#12 Improve unscented transform utilities
  src/BayesFilters/include/BayesFilters/sigma_point.h
  src/BayesFilters/src/sigma_point.cpp
Labels: documentation, enhancement

#13 Implement Gaussian filtering
  CHANGELOG.md
  src/BayesFilters/CMakeLists.txt
  src/BayesFilters/include/BayesFilters/GaussianCorrection.h
  src/BayesFilters/include/BayesFilters/GaussianFilter.h
  src/BayesFilters/include/BayesFilters/GaussianPrediction.h
  src/BayesFilters/include/BayesFilters/KFCorrection.h
  src/BayesFilters/include/BayesFilters/KFPrediction.h
  src/BayesFilters/include/BayesFilters/KalmanFilter.h
  src/BayesFilters/include/BayesFilters/SPCorrection.h
  src/BayesFilters/include/BayesFilters/SPPrediction.h
  src/BayesFilters/include/BayesFilters/UKFCorrection.h
  src/BayesFilters/include/BayesFilters/UKFPrediction.h
  src/BayesFilters/src/GaussianCorrection.cpp
  src/BayesFilters/src/GaussianFilter.cpp
  src/BayesFilters/src/GaussianPrediction.cpp
  src/BayesFilters/src/KFCorrection.cpp
  src/BayesFilters/src/KFPrediction.cpp
  src/BayesFilters/src/KalmanFilter.cpp
  src/BayesFilters/src/SPCorrection.cpp
  src/BayesFilters/src/SPPrediction.cpp
  src/BayesFilters/src/UKFCorrection.cpp
  src/BayesFilters/src/UKFPrediction.cpp
  test/CMakeLists.txt
  test/test_KF/CMakeLists.txt
  test/test_KF/main.cpp
  test/test_UKF/CMakeLists.txt
  test/test_UKF/main.cpp
  test/test_mixed_KF_UKF/CMakeLists.txt
  test/test_mixed_KF_UKF/main.cpp
  test/test_mixed_UKF_KF/CMakeLists.txt
  test/test_mixed_UKF_KF/main.cpp
Labels: enhancement

#14 Improve particle filtering
  CHANGELOG.md
  src/BayesFilters/CMakeLists.txt
  src/BayesFilters/include/BayesFilters/GPFCorrection.h
  src/BayesFilters/include/BayesFilters/GPFPrediction.h
  src/BayesFilters/include/BayesFilters/GaussianCorrection.h
  src/BayesFilters/include/BayesFilters/GaussianPrediction.h
  src/BayesFilters/include/BayesFilters/SIS.h
  src/BayesFilters/include/BayesFilters/WhiteNoiseAcceleration.h
  src/BayesFilters/include/BayesFilters/utils.h
  src/BayesFilters/src/GPFCorrection.cpp
  src/BayesFilters/src/GPFPrediction.cpp
  src/BayesFilters/src/InitSurveillanceAreaGrid.cpp
  src/BayesFilters/src/Resampling.cpp
  src/BayesFilters/src/ResamplingWithPrior.cpp
  src/BayesFilters/src/SIS.cpp
  src/BayesFilters/src/UpdateParticles.cpp
  src/BayesFilters/src/WhiteNoiseAcceleration.cpp
  src/BayesFilters/src/utils.cpp
  test/CMakeLists.txt
  test/test_UPF/CMakeLists.txt
  test/test_UPF/main.cpp
Labels: enhancement

#16 Improve logging facilities
  CHANGELOG.md
  src/BayesFilters/include/BayesFilters/Logger.h
  src/BayesFilters/include/BayesFilters/SIS.h
  src/BayesFilters/include/BayesFilters/SimulatedLinearSensor.h
  src/BayesFilters/include/BayesFilters/SimulatedStateModel.h
  src/BayesFilters/src/GaussianFilter.cpp
  src/BayesFilters/src/Logger.cpp
  src/BayesFilters/src/SIS.cpp
  src/BayesFilters/src/SimulatedLinearSensor.cpp
  src/BayesFilters/src/SimulatedStateModel.cpp
  test/test_KF/main.cpp
  test/test_UKF/main.cpp
  test/test_UPF/main.cpp
  test/test_mixed_KF_SUKF/main.cpp
  test/test_mixed_KF_UKF/main.cpp
  test/test_mixed_UKF_KF/main.cpp
Labels: enhancement

#17 Update SIS implementation
  CHANGELOG.md
  src/BayesFilters/CMakeLists.txt
  src/BayesFilters/include/BayesFilters/BootstrapCorrection.h
  src/BayesFilters/include/BayesFilters/ParticleFilter.h
  src/BayesFilters/include/BayesFilters/SIS.h
  src/BayesFilters/src/BootstrapCorrection.cpp
  src/BayesFilters/src/ParticleFilter.cpp
  src/BayesFilters/src/SIS.cpp
  test/CMakeLists.txt
  test/test_ParticleFilter/CMakeLists.txt
  test/test_ParticleFilter/main.cpp
  test/test_SIS/main.cpp
  test/test_SIS_Decorators/main.cpp
  test/test_UKF/main.cpp
  test/test_UPF/main.cpp
Labels: enhancement

#20 Fix compile warnings and simplify tests
  CHANGELOG.md
  src/BayesFilters/include/BayesFilters/KFCorrection.h
  src/BayesFilters/include/BayesFilters/WhiteNoiseAcceleration.h
  src/BayesFilters/src/GaussianFilter.cpp
  src/BayesFilters/src/SIS.cpp
  src/BayesFilters/src/UKFCorrection.cpp
  test/CMakeLists.txt
  test/test_KF/CMakeLists.txt
  test/test_KF/main.cpp
  test/test_SIS/CMakeLists.txt
  test/test_SIS/main.cpp
  test/test_SIS_Decorators/main.cpp
  test/test_UKF/CMakeLists.txt
  test/test_UKF/main.cpp
  test/test_UPF/CMakeLists.txt
  test/test_UPF/main.cpp
  test/test_mixed_KF_SUKF/CMakeLists.txt
  test/test_mixed_KF_SUKF/main.cpp
  test/test_mixed_KF_UKF/CMakeLists.txt
  test/test_mixed_KF_UKF/main.cpp
  test/test_mixed_UKF_KF/CMakeLists.txt
  test/test_mixed_UKF_KF/main.cpp
Labels: bug, documentation, enhancement
